#!/bin/bash

startMonth=$1
startYear=$2
endMonth=$3
endYear=$4

#TODO:If not given, then false
if [ $# -ge 5 ]
then
    bandwidth=$5
else
    bandwidth=false
fi
echo $bandwidth
bandwidth=false

#runs findTor_Parallel to get list of ip addresses associated with tor relays
#for the given range of months
#writes this list to data/formatted/torIPLists/torIPList-{year}-{month}
echo "Running findTor_Parallel"
echo "Finding bandwidth: $bandwidth"
python3 findTor_Parallel.py -s $startMonth $startYear -e $endMonth $endYear -b $bandwidth

#Look through each file created in findTor_Parallel and keep only unique ip addresses

while [ $startYear -lt $endYear ] || [ $startMonth -le $endMonth -a $startYear == $endYear ]
do
    if [ ${#startMonth} -lt 2 ]; then formattedStartMonth="0$startMonth"; else formattedStartMonth="$startMonth"; fi
   
    TorIPList=data/formatted/torIPLists/torIPList-${startYear}-${formattedStartMonth}
    
    TorIPListSorted="data/formatted/torIPLists/torIPListSorted-${startYear}-${formattedStartMonth}"
    
    if $bandwidth ;then #Sum the bandwidths by IP address
        awk -F' ' '{a[$1] += $2} END { for (x in a) printf "%s %s\n", x, a[x] }' < $TorIPList > $TorIPListSorted
    else #Get only unique IP addresses
        sort $TorIPList | uniq > $TorIPListSorted 
    fi

    ((startMonth++))
    if [ $startMonth = 13 ]
    then
        wait
        ((startYear++))
        ((startMonth=1))
    fi
done 

echo "Running sortTree_Parallel for ASes"
#map list of tor IPs to AS mappings
startMonth=$1
startYear=$2
endMonth=$3
endYear=$4

#run to create tree of ASes and search for each IP's AS, returns all ASes w/ tor relays
#saves to data/formatted/asLists/listOfAS-{year}-{month}
python3 sortTree_Parallel.py -s $startMonth $startYear -e $endMonth $endYear -b $bandwidth 

#creates file results to save number of tor relays for each month
if [ ${#startMonth} -lt 2 ]; then formattedStartMonth="0$1"; else formattedStartMonth="$1"; fi
if [ ${#endMonth} -lt 2 ]; then formattedEndMonth="0$3"; else formattedEndMonth="$3"; fi
results="data/results/results-${2}${formattedStartMonth}-${4}${formattedEndMonth}.txt"
> $results


#Creates file "data/results/results-${startYear}${formattedStartMonth}-${endYear}${formattedEndMonth}.txt"
while [ $startYear -lt $endYear ] || [ $startMonth -le $endMonth -a $startYear == $endYear ]
do
    if [ ${#startMonth} -lt 2 ]; then formattedStartMonth="0$startMonth"; else formattedStartMonth="$startMonth"; fi

    TorIPListSorted="data/formatted/torIPLists/torIPListSorted-${startYear}-${formattedStartMonth}"
    listOfAS="data/formatted/asLists/listOfAS-${startYear}-${formattedStartMonth}" 
       
    num=$(sort $TorIPListSorted | uniq -c | wc -l) #TODO: ADDED uniq - c to chekc
    uniqueAS=$(sort $listOfAS | uniq -c | wc -l)

    uniqueListOfAS="data/formatted/asLists/sortedListOfAS-${startYear}-${formattedStartMonth}"
    sort $listOfAS | uniq > $uniqueListOfAS 

    echo "${formattedStartMonth}-01-${startYear} ${num} ${uniqueAS}" >> $results

    ((startMonth++))
    if [ $startMonth = 13 ]
    then
        wait
        ((startYear++))
        ((startMonth=1))
    fi
done

#TODO: look at all files and save to uniqueTorIP-$2$1-$4$3.txt
echo "findData finished running."

#rm data/formatted/asLists/listOfAS*
#rm data/formatted/torIPLists/torIPLists-*